export const QUOTES = [
    "It's just consolidating before the next leg up.",
    "Red days are for accumulation.",
    "The devs are building.",
    "I didn't lose, I increased my conviction.",
    "Only paper hands sell the bottom.",
    "Weekly still looks bullish.",
    "Market makers are hunting stops.",
    "Wick below support to shake out weak hands.",
    "Smart money is accumulating quietly.",
    "It's a healthy correction.",
    "Zoom out, we're still early.",
    "FUD is temporary, tech is forever.",
    "Giga-brain buy zone.",
    "This is the last dip before the rip.",
    "Liquidity was needed for the next move.",
    "I'm not trapped, just staking.",
    "My average is down, so risk is down.",
    "Whales want your bags.",
    "Narrative rotation is coming back.",
    "We're so back after this retest.",
    "WAGMI, just give it time.",
    "Capitulation is bullish.",
    "They're shaking out weak hands.",
    "This wick was engineered.",
    "ETF flows will rescue us.",
    "The halving will fix it.",
    "Alts run after BTC.",
    "BTC dominance is about to reverse.",
    "It's a spring, not a breakdown.",
    "Hidden bullish divergence on the RSI.",
    "0.618 fib held perfectly.",
    "Just a liquidity sweep.",
    "Bull flag on the higher timeframe.",
    "Monthly still prints higher lows.",
    "Weekly close will change everything.",
    "NY open usually pumps.",
    "Asia dumped so US can buy.",
    "Max pain is up.",
    "CME gap needs filling first.",
    "Funding flipped negative, send it.",
    "Open interest got wiped, clean slate.",
    "Whales are accumulating OTC.",
    "Exchange reserves at multi-year lows.",
    "Supply shock incoming.",
    "Real yield narrative coming back.",
    "Rotation into quality soon.",
    "This is just volatility compression.",
    "Wyckoff accumulation is playing out.",
    "Inverse Cramer is undefeated.",
    "Mt. Gox unlock is priced in.",
    "Regulatory clarity is around the corner.",
    "Rate cuts will reignite risk.",
    "DXY is topping out, risk on.",
    "Q4 seasonality is our friend.",
    "Santa rally loading.",
    "One more dip to nuke leverage.",
    "Bears are about to get rekt.",
    "Higher low confirmed.",
    "Breakout retest before continuation.",
    "That was just a stop hunt.",
    "KOLs haven't noticed yet.",
    "Smart money is buying the fear.",
    "When it rips, it rips fast.",
    "This range will resolve up.",
    "Volume is building quietly.",
    "Narrative shift is imminent.",
    "Real builders thrive in bears.",
    "Airdrop season will bring liquidity.",
    "Unlocks were absorbed easily.",
    "Tokenomics improved after the revamp.",
    "New partnerships soon.",
    "Team is shipping in stealth.",
    "The chart is coiling.",
    "Long-term holders aren't selling.",
    "MVRV back to safe levels.",
    "Realized price acting as support.",
    "Hash rate at ATH is bullish.",
    "Miner capitulation is over.",
    "The bottom was a generational opportunity.",
    "We're early. Again."
  ]
  